### ISSUE TITLE
RSS aggregator function

### ISSUE THREAD

**Issue by tyohan** [Shuvayatra/migration-web#2]
I check the CMS and haven't see any function to aggregate RSS content. Do you still develop it or it's hiding somewhere?

**Comment by mojbenzcar** [comment]
@fixed

**Comment by prashantsh** [comment]
@tyohan we have the RSS functionality however we still need to work out the preview as it is now only showing as link.

**Comment by tyohan** [comment]
I still have another 11 flight now. Please keep me update about this how it goes. So i can check it and try to code it too when i arrive

**Comment by tyohan** [comment]
@prashantsh there is OEmbed library that can help on preview. Tumblr support OEmbed too. One PHP library that you can use is https://github.com/oscarotero/Embed . 

This is one how it works on Tumblr https://www.tumblr.com/oembed/1.0?url=http://shuvayatrablog.tumblr.com/post/144402156798

Let me know what do you think?
